server:
  servlet:
    context-path: /api/v1
    session:
      timeout: 60s
  port: 8123
spring:
  application:
    name: qapi
  datasource:
    url: jdbc:mysql://localhost:3306/qapi
    username: root
    password: Qkj980518
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapperxml/**/*.xml
  type-aliases-package: com.minton.qapi.**.model
  scan:
    base-package: com.minton.qapi.**.mapper
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
springdoc:
# get请求多参数时不需要添加额外的@ParameterObject和@Parameter注解
  default-flat-param-object: true
# 启用swaggerUI
  swagger-ui:
    enabled: true
# 启用文档，默认开启
  api-docs:
    enabled: true
